version: 0.0
os: linux

files:             
  - source: ./webapp/target/ROOT.war
    destination: /opt/tomcat/webapps
  - source: ./cloudWatchRestart.sh
    destination: /home/centos
  - source: ./infrastructure/aws/cloudwatch/cloudwatch-config.json
    destination: /opt/cloudwatch-config.json

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
  AfterInstall:
   - location: ./cloudWatchRestart.sh
     timeout: 360
     runas: centos
