---



AWSTemplateFormatVersion: '2010-09-09'

  

Parameters:

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: csye6225-fall2018-assignment3
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: EC2 instance type must be valid.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
 
  SubnetA:
    Type: String
    
  SubnetB:
    Type: String
    
  myVPC:
    Type: String  




    



Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      AvailabilityZone: us-east-1a
      SubnetId: !Ref SubnetA
      SecurityGroupIds:
      - Ref: WebServerSecurityGroup

      KeyName:
        Ref: KeyName
      ImageId: ami-9887c6e7
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: gp2
          VolumeSize: '20'

          



  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access on port 22, 80 and 443
      VpcId: !Ref myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp:
          Ref: SSHLocation         



  RDSInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access on port 3306
      VpcId: !Ref myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        SourceSecurityGroupId: !Ref WebServerSecurityGroup

  myDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      TableName: "csye6225-fall2018"
      KeySchema: 
      - AttributeName: "id"
        KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: csye6225-fall2018-reubenn.me.csye6225.com

  myRDSinstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100 
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: "csye6225-Fall2018"
      DBSubnetGroupName: !Ref myDBSubnetGroup
      DBName: "csye6225"
      Engine: MySQL
      MasterUsername: "csye6225master"
      MasterUserPassword: "csye6225password"
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups: 
        - !GetAtt RDSInstanceSecurityGroup.GroupId
        
  myDBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "description"
      SubnetIds: 
        - !Ref SubnetA
        - !Ref SubnetB

          

          

Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2Instance

  SecurityGroupID:    Description: SecurityGroupId of newly created group
    Value:
      Ref: RDSInstanceSecurityGroup



  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - AvailabilityZone

