# Create VPC with the help of Cloud formation

Parameters:
  CidrBlock:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: "VPC CIDR Details"
    Type: String
  AvailabilityZoneA:
    Description: "1st subnet Availability zone"
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZoneB:
    Description: "2nd subnet Availability zone"
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZoneC:
    Description: "3rd subnet Availability zone"
    Type: AWS::EC2::AvailabilityZone::Name
  SubnetCIDRA:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/24
    Description: "Subnet1 CIDR Block details"
    Type: String
  SubnetCIDRB:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.1.0/24
    Description: "Subnet2 CIDR Block details"
    Type: String
  SubnetCIDRC:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.2.0/24
    Description: "Subnet3 CIDR Block details"
    Type: String



Resources:
  csyeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZoneA
      VpcId: !Ref csyeVPC
      CidrBlock: !Ref SubnetCIDRA
      MapPublicIpOnLaunch: true
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZoneB
      VpcId: !Ref csyeVPC
      CidrBlock: !Ref SubnetCIDRB
      MapPublicIpOnLaunch: true
  SubnetC:
     Type: AWS::EC2::Subnet
     Properties:
       AvailabilityZone: !Ref AvailabilityZoneC
       VpcId: !Ref csyeVPC
       CidrBlock: !Ref SubnetCIDRC
       MapPublicIpOnLaunch: true
  InternetGateway:
     Type: AWS::EC2::InternetGateway
  InternetGatewayAttach:
     Type: AWS::EC2::VPCGatewayAttachment
     Properties:
       VpcId: !Ref csyeVPC
       InternetGatewayId: !Ref InternetGateway
  RouteTable:
     Type: AWS::EC2::RouteTable
     Properties:
       VpcId: !Ref csyeVPC
  InternetRoute:
     Type: AWS::EC2::Route
     DependsOn: InternetGateway
     Properties:
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId: !Ref InternetGateway
       RouteTableId: !Ref RouteTable
  SubnetARouteTableAssociation:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       RouteTableId: !Ref RouteTable
       SubnetId: !Ref SubnetA
  SubnetBRouteTableAssociation:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       RouteTableId: !Ref RouteTable
       SubnetId: !Ref SubnetB
  SubnetCRouteTableAssociation:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       RouteTableId: !Ref RouteTable
       SubnetId: !Ref SubnetC
